[package]
name = "ahistorics"
version = "0.1.0"
authors = ["z"]

[dependencies]
clippy = {version = "*", optional = true}

piston = "*"
piston2d-graphics = "*"
piston2d-opengl_graphics = "*"
pistoncore-sdl2_window = "*"

rand = "*"

vecmath = "*"

[features]
default = []
